### ISSUE TITLE
ERROR NullInjectorError: R3InjectorError(AppModule)[SnotifireService -> snotifireConfig -> snotifireConfig -> snotifireConfig]

### ISSUE THREAD

**Issue by MohammedAldosari** [ccpatrut/ngx-snotifire#7]
when I run the application I'm getting the below error 

```
main.ts:12 ERROR NullInjectorError: R3InjectorError(AppModule)[SnotifireService -> snotifireConfig -> snotifireConfig -> snotifireConfig]: 
  NullInjectorError: No provider for snotifireConfig!
    at NullInjector.get (core.mjs:7599:27)
    at R3Injector.get (core.mjs:8020:33)
    at R3Injector.get (core.mjs:8020:33)
    at R3Injector.get (core.mjs:8020:33)
    at injectInjectorOnly (core.mjs:634:33)
    at Module.ɵɵinject (core.mjs:638:60)
    at Object.SnotifireService_Factory [as factory] (ngx-snotifire.mjs:485:102)
    at R3Injector.hydrate (core.mjs:8121:35)
    at R3Injector.get (core.mjs:8009:33)
    at ChainedInjector.get (core.mjs:12179:36)
```

**Comment by ccpatrut** [comment]
![image](https://user-images.githubusercontent.com/44428503/213909326-ccb138a2-80c8-4347-ac0a-abddba594e35.png)


In your module.ts file you should have something like this, note the providers list? 

Can you confirm you added it?

**Comment by ccpatrut** [comment]
I just tested the latest version the other day in another poject of mine and seems to be working. 

A few things were missing indeed
